INSERT INTO USER(EMAIL) VALUES('e1@google.com');
INSERT INTO USER(EMAIL) VALUES('e2@naver.com');
INSERT INTO USER(EMAIL) VALUES('e3@daum.com');

INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W1', 'T1', 'C1', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W2', 'T2', 'C2', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W3', 'T3', 'C3', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W4', 'T4', 'C4', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W5', 'T5', 'C5', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W6', 'T6', 'C6', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W7', 'T7', 'C7', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W8', 'T8', 'C8', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W9', 'T9', 'C9', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W10', 'T10', 'C10', CURRENT_TIMESTAMP(), 0);
INSERT INTO BOARD(WRITER,TITLE,CONTENT,REG_DATE,HIT_COUNT) VALUES('W11', 'T11', 'C11', CURRENT_TIMESTAMP(), 0);
